// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNLhRRZSWzyatJ9KkSnIraW0ZIWNWhGM',
    appId: '1:833913701133:web:68baeb1025b82ee98ee644',
    messagingSenderId: '833913701133',
    projectId: 'chat-33c48',
    authDomain: 'chat-33c48.firebaseapp.com',
    storageBucket: 'chat-33c48.appspot.com',
    measurementId: 'G-0R7TJR8YHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwUyJhfF1c4WDrn2m-aq7M8HyEONmoUKk',
    appId: '1:833913701133:android:6faac68d4add2b6a8ee644',
    messagingSenderId: '833913701133',
    projectId: 'chat-33c48',
    storageBucket: 'chat-33c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3YtlmHRmGSyxwiDwERGjlCED6LJ7-rg',
    appId: '1:833913701133:ios:dc7be6ee7f40d7fc8ee644',
    messagingSenderId: '833913701133',
    projectId: 'chat-33c48',
    storageBucket: 'chat-33c48.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );
}
